version: '3.8'

services:
  client-shop:
    image: client-shop:latest
    build:
      context: .
      dockerfile: clientshop/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - keycloak
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/intershop
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD_FILE: /run/secrets/db_password
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/intershop
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: http://keycloak:8080/realms/intershop/protocol/openid-connect/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/intershop/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/intershop/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: intershop-client
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: xODGIdLaADbA3jcBBa4HV1pa2MAeDxMQ
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_PROVIDER: keycloak
    secrets:
        - db_password
    restart: always

  server-payment:
    image: server-payment:latest
    build:
      context: .
      dockerfile: serverpayment/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/intershop/protocol/openid-connect/certs
    depends_on:
      - client-shop
      - keycloak

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: intershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm

secrets:
  db_password:
    file: ./secrets/db_password.txt