spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: postgres
    password: serik1995

  redis:
    host: redis
    port: 6379

  liquibase:
    url: jdbc:postgresql://localhost:5432/intershop
    user: postgres
    password: serik1995
    driver-class-name: org.postgresql.Driver
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never
  # Security
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: intershop-client
            client-secret: xODGIdLaADbA3jcBBa4HV1pa2MAeDxMQ
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/intershop/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/intershop/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8180/realms/intershop/protocol/openid-connect/certs

payment-app:
#  host: localhost
  host: server-payment
  port: 8081